name: variables
on: 
    workflow_dispatch:
env:
  WORKFLOW_VAR: 'I am a workflow env var'
  OVERWRITTEN: 'I will be overwritten'
jobs:
    echo:
        runs-on: ubuntu-latest
        env:
          JOB_VAR: 'I am a job env var'
          OVERWRITTEN: 'I have been overwritten at the job level'
        steps:
            - name: Print variables
              env:
                STEP_VAR1: 'I am a step env var name STEP_VAR1'
                STEP_VAR2: 'I am a step env var name STEP_VAR2'
              run: |
                echo "step env var 1 : ${{ env.STEP_VAR1}}"
                echo "step env var 2 : ${{ env.STEP_VAR2}}"
                echo "Job env var  : ${{ env.JOB_VAR}}"
                echo "Workflow env var : ${{ env.WORKFLOW_VAR}}"
                echo "OVERWRITTEN env var : ${{ env.OVERWRITTEN}}"
            - name: Overwrite job variable
              env:
                OVERWRITTEN: 'I have been overwritten at the step level'
              run: |
                echo  "OVERWRITTEN env var : ${{ env.OVERWRITTEN}}"

              