name: controlling-execution-flow

on: 
    workflow_dispatch:
      inputs:
        pass-unit-tests:
          type: boolean
          description: Wether unit tests will pass or not
          default: true

jobs:
    lint-build:
      runs-on: ubuntu-latest
      steps:
        - name: Lint and build
          run: echo "Linting and building project"
    test:
      runs-on: ubuntu-latest
      steps:
        - name: Running unit test
          run: echo "Running tests... "
        - name: Failing tests
          if: ${{ !inputs.pass-unit-tests}}
          run: exit 1
    deploy-nonprod:
      runs-on: ubuntu-latest
      needs:
        - lint-build
        - test
      steps:
        - name: Deploying to nonprod
          run: echo "Deploying to nonprod... "
    e2e-tests:
      runs-on: ubuntu-latest
      needs:
        - deploy-nonprod
      steps:
        - name: Running E2E test
          run: echo "Running E2E tests... "
    deploy-prod:
      runs-on: ubuntu-latest
      needs:
        - e2e-tests
      steps:
        - name: Deploying to prod
          run: echo "Deploying to prod... "

              